### PR TITLE
Add README art

### LINKED ISSUE #1: readme art
bitmoji

### PR DESCRIPTION
**Pull request by emilymdubois**
A departure gift 🎁

Closes #1.
@vsmart for review.

### CODE REVIEW

**Comment by rclark** [comment]
😆 

Thanks @emilymdubois !

**Comment by vsmart** [comment]
😍 ❤️ 🐦 thank you @emilymdubois !!!

**Comment by springmeyer** [comment]
❤️

**Comment by mapsam** [comment]
🤣 ❤️

**Pull request merged**
